Repository googleapis/python-language, pull requests merged in 2021-04, with the labels that each got.

#87 chore: start tracking obsolete files
  synth.metadata
Labels: api: language, cla: yes, context: full

#90 chore: Add license headers for python config files
  .pre-commit-config.yaml
  docs/conf.py
  synth.metadata
Labels: api: language, automerge, cla: yes, context: full

#89 chore: Migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .pre-commit-config.yaml
  docs/conf.py
  owlbot.py
  synth.metadata
Labels: api: language, automerge, cla: yes

#93 chore: prevent normalization of semver versioning
  setup.py
Labels: api: language, cla: yes

#99 chore(revert): revert preventing normalization
  setup.py
Labels: api: language, cla: yes
